In [ ]:
import numpy as np #importa la biblioteca NumPy, que es muy útil para trabajar con
#matrices, vectores y calculos numericos.

# Definir la matriz A
A = np.array([[1, 2], [3, 4]]) #crea una matriz 2x2 con los valores
                               #se usa np.array para definir como matriz NumPy

# Mostrar A^1
print("A^1:")
print(A)#Muestra la matriz original, que corresponde a A^1.

# Inicializar la variable con A^1
An = A.copy() #Guarda una copia de A en una nueva variable An, que se usara para calcular las siguientes potencias
              #Es importante usar .copy() para que no se modifique A por accidente

# Calcular y mostrar A^n para n=2 hasta n=10
for n in range(2, 11): #genera los númers del 2 al 10
    An = A @ An #Multiplica la matriz A por la potencia anterior (An)
                #El simbolo @ significa multiplicacion de matrices (no elemento a elemento)
                #Luego imprime el resultado A^n.
    print(f"A^{n}:")
    print(An)

#se usa @ An para la multiplicacion de matrices
#(mejor que * que haria multiplicacion elemento a elmento)


A^1:
[[1 2]
 [3 4]]
A^2:
[[ 7 10]
 [15 22]]
A^3:
[[ 37  54]
 [ 81 118]]
A^4:
[[199 290]
 [435 634]]
A^5:
[[1069 1558]
 [2337 3406]]
A^6:
[[ 5743  8370]
 [12555 18298]]
A^7:
[[30853 44966]
 [67449 98302]]
A^8:
[[165751 241570]
 [362355 528106]]
A^9:
[[ 890461 1297782]
 [1946673 2837134]]
A^10:
[[ 4783807  6972050]
 [10458075 15241882]]


In [ ]:
import numpy as np

# Define la matriz A
A = np.array([[1, 2], [3, 4]])

# Inicializa An como A
An = A

# Imprime A^1
print("A^1:")
print(An)

# Bucle para calcular e imprimir desde A^2 hasta A^10
for n in range(2, 11):
    An = A @ An
    print(f"A^{n}:")
    print(An)



A^1:
[[1 2]
 [3 4]]
A^2:
[[ 7 10]
 [15 22]]
A^3:
[[ 37  54]
 [ 81 118]]
A^4:
[[199 290]
 [435 634]]
A^5:
[[1069 1558]
 [2337 3406]]
A^6:
[[ 5743  8370]
 [12555 18298]]
A^7:
[[30853 44966]
 [67449 98302]]
A^8:
[[165751 241570]
 [362355 528106]]
A^9:
[[ 890461 1297782]
 [1946673 2837134]]
A^10:
[[ 4783807  6972050]
 [10458075 15241882]]


In [8]:
import numpy as np #Importa la libreria Numpy, que se usa para trabajar con matrices
                    #y operaciones eficientes

#Matriz de adyacencia (ejemplo de un grafo con 4 nodos)

# Definir la matriz de adyacencia
A = np.array([
    [0, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 0, 0, 1],
    [1, 0, 0, 0]
]) #Se define la matriz de adyacencia del grafo. Cada fila repesenta un nodo de origen
   #y cada columna un nodo de destino.

print("Matriz A (adyacencia):\n", A) #Muestra la matriz original, que representa los caminos de longitud 1 entre nodos.

# Mostrar las potencias de A hasta A^10
An = A.copy() #Se crea una copia de la matriz original para no modificarla directamente
              #esta copia se usara para calcular las potencias sucesivas


#Bucle para calcular de A^2 a A^10
for t in range(2, 11): #es bucle que va desde t=2 hasta t=10
    An = np.matmul(An, A) #multiplica la matriz actual por la original, esto equivale a calcular A^t
    print(f"\nA^{t} (caminos de longitud {t}):")
    print(An)

#Este código permite analizar cómo se propagan los caminos en un grafo
#a medida que aumentas la longitud de los trayectos.

Matriz A (adyacencia):
 [[0 1 0 0]
 [1 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]

A^2 (caminos de longitud 2):
[[1 0 1 0]
 [0 1 0 1]
 [1 0 0 0]
 [0 1 0 0]]

A^3 (caminos de longitud 3):
[[0 1 0 1]
 [2 0 1 0]
 [0 1 0 0]
 [1 0 1 0]]

A^4 (caminos de longitud 4):
[[2 0 1 0]
 [0 2 0 1]
 [1 0 1 0]
 [0 1 0 1]]

A^5 (caminos de longitud 5):
[[0 2 0 1]
 [3 0 2 0]
 [0 1 0 1]
 [2 0 1 0]]

A^6 (caminos de longitud 6):
[[3 0 2 0]
 [0 3 0 2]
 [2 0 1 0]
 [0 2 0 1]]

A^7 (caminos de longitud 7):
[[0 3 0 2]
 [5 0 3 0]
 [0 2 0 1]
 [3 0 2 0]]

A^8 (caminos de longitud 8):
[[5 0 3 0]
 [0 5 0 3]
 [3 0 2 0]
 [0 3 0 2]]

A^9 (caminos de longitud 9):
[[0 5 0 3]
 [8 0 5 0]
 [0 3 0 2]
 [5 0 3 0]]

A^10 (caminos de longitud 10):
[[8 0 5 0]
 [0 8 0 5]
 [5 0 3 0]
 [0 5 0 3]]
